version: 2
updates:
  - package-ecosystem: npm
    directory: "client"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "server"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10