// auth.ts
export const FETCH_USER = 'FETCH_USER'
export const LOGOUT = 'LOGOUT'
export const CHANGE_USER_PROPS = 'CHANGE_USER_PROPS'
export const CHANGE_USER_AVATAR = 'CHANGE_USER_AVATAR'
export const CHANGE_USER_VERIFICATION = 'CHANGE_USER_VERIFICATION'
