# Интеграционные запросы для Портала https://cbias.ru

# curl -X 'GET'
#  'http://localhost:8000/external/v1/projects'
#  -H 'accept: application/json'
#  -H 'X-Authentication: 78MOl7ynTbcAPPZZDg5R'

GET http://localhost:8000/external/v1/projects
Authorization: 78MOl7ynTbcAPPZZDg5R