# Generated by Django 3.2.12 on 2022-03-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitation',
            old_name='meta',
            new_name='cell',
        ),
        migrations.AddField(
            model_name='period',
            name='privately',
            field=models.BooleanField(default=False, help_text='Приватность полей'),
        ),
        migrations.AlterField(
            model_name='columndimension',
            name='background',
            field=models.CharField(default='#FFFFFF', help_text='Цвет фона', max_length=7),
        ),
        migrations.AlterField(
            model_name='columndimension',
            name='color',
            field=models.CharField(default='#000000', help_text='Цвет индекса', max_length=7),
        ),
        migrations.AlterField(
            model_name='rowdimension',
            name='background',
            field=models.CharField(default='#FFFFFF', help_text='Цвет фона', max_length=7),
        ),
        migrations.AlterField(
            model_name='rowdimension',
            name='color',
            field=models.CharField(default='#000000', help_text='Цвет индекса', max_length=7),
        ),
        migrations.AlterField(
            model_name='rowdimension',
            name='parent',
            field=models.ForeignKey(help_text='Родительское правило', null=True, on_delete=django.db.models.deletion.CASCADE, to='dcis.rowdimension'),
        ),
        migrations.AlterUniqueTogether(
            name='mergedcell',
            unique_together={('min_col', 'min_row', 'sheet')},
        ),
    ]
