# Generated by Django 3.2.12 on 2022-03-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='value',
            name='dcis_value_documen_92ad90_idx',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='background',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='color',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='horizontal_align',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='italic',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='size',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='strike',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='strong',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='underline',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='vertical_align',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='background',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='color',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='horizontal_align',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='italic',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='size',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='strike',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='strong',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='underline',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='vertical_align',
        ),
        migrations.AddField(
            model_name='cell',
            name='editable',
            field=models.BooleanField(default=True, help_text='Редактируемая ячейка'),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='condition',
            field=models.CharField(choices=[('lt', '<'), ('gt', '>'), ('equal', '='), ('lte', '<='), ('gte', '>=')], default='equal', help_text='Состояние', max_length=8),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='operator',
            field=models.CharField(choices=[('and', 'and'), ('or', 'or')], default='and', help_text='Оператор', max_length=3),
        ),
        migrations.AlterField(
            model_name='rowdimension',
            name='index',
            field=models.PositiveIntegerField(help_text='Индекс строки'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['column'], name='dcis_cell_column__d7e31f_idx'),
        ),
        migrations.AddIndex(
            model_name='value',
            index=models.Index(fields=['document', 'column'], name='dcis_value_documen_90a766_idx'),
        ),
    ]
