# Generated by Django 3.2.12 on 2022-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0002_auto_20220313_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='border_color',
            field=models.JSONField(help_text='Цвет границ', null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='border_style',
            field=models.JSONField(help_text='Стили границ', null=True),
        ),
    ]
