# Generated by Django 3.2.12 on 2022-03-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcis', '0003_auto_20220315_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('period', 'version', 'content_type', 'object_id')},
        ),
    ]
