# Generated by Django 3.2.12 on 2022-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0005_alter_document_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.CharField(choices=[('preparation', 'preparation'), ('open', 'open'), ('close', 'close')], default='preparation', help_text='Статус проекта', max_length=16),
        ),
        migrations.AlterField(
            model_name='period',
            name='expiration',
            field=models.DateField(help_text='Дата окончания', null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start',
            field=models.DateField(help_text='Дата начала', null=True),
        ),
    ]
