# Generated by Django 3.2.12 on 2022-03-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0006_alter_period_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',)},
        ),
    ]
