# Generated by Django 3.2.12 on 2022-03-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0007_auto_20220323_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mergedcell',
            options={'ordering': ('min_col', 'min_row')},
        ),
        migrations.AlterUniqueTogether(
            name='mergedcell',
            unique_together=set(),
        ),
    ]
