# Generated by Django 3.2.12 on 2022-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0008_auto_20220325_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdimension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата обновления'),
        ),
    ]
