# Generated by Django 3.2.12 on 2022-03-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0009_rowdimension_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentstatus',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='documentstatus',
            index=models.Index(fields=['document', 'status'], name='dcis_docume_documen_00c5bd_idx'),
        ),
    ]
