# Generated by Django 3.2.12 on 2022-04-06 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcis', '0010_auto_20220329_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privilege',
            options={'ordering': ('name', 'id')},
        ),
        migrations.RemoveIndex(
            model_name='division',
            name='dcis_divisi_content_18f5d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='dcis_docume_content_ff0c1c_idx',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='columndimension',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='division',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rowdimension',
            name='content_type',
        ),
        migrations.AddField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(default=31, help_text='Тип дивизиона', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='rowdimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Идентификатор дивизиона'),
        ),
        migrations.AlterField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Идентификатор дивизиона', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('period', 'version', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
    ]
