# Generated by Django 3.2.12 on 2022-03-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcis', '0010_auto_20220329_1154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='division',
            name='dcis_divisi_content_18f5d6_idx',
        ),
        migrations.RemoveField(
            model_name='division',
            name='content_type',
        ),
        migrations.AddField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['content_type', 'object_id'], name='dcis_projec_content_dc8f6d_idx'),
        ),
    ]
