# Generated by Django 3.2.12 on 2022-03-30 21:21

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcis', '0010_auto_20220329_1154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='division',
            name='dcis_divisi_content_18f5d6_idx',
        ),
        migrations.RemoveField(
            model_name='division',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('period', 'version', 'object_id')},
        ),
        migrations.AddField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(default=ContentType.objects.get_by_natural_key('devind_dictionaries', 'department').id, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        )
    ]
