# Generated by Django 3.2.13 on 2022-04-18 16:52

import apps.dcis.models.project
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcis', '0011_auto_20220406_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(default=apps.dcis.models.project.default_content_type, help_text='Тип дивизиона', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
