# Generated by Django 3.2.12 on 2022-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0012_alter_project_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='payload',
            field=models.JSONField(help_text='Дополнительные данные', null=True),
        ),
    ]
