# Generated by Django 3.2.13 on 2022-04-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0014_auto_20220425_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columndimension',
            name='auto_size',
        ),
    ]
