# Generated by Django 3.2.12 on 2022-04-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0015_remove_columndimension_auto_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdimension',
            name='fixed',
            field=models.BooleanField(default=False, help_text='Фиксация строки'),
        ),
        migrations.AddField(
            model_name='rowdimension',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрытие строки'),
        ),
        migrations.AlterField(
            model_name='columndimension',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрытие колонки'),
        ),
        migrations.AlterField(
            model_name='rowdimension',
            name='height',
            field=models.PositiveIntegerField(help_text='Высота строки', null=True),
        ),
    ]
