# Generated by Django 3.2.13 on 2022-06-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0015_remove_columndimension_auto_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodgroup',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('period', 'object_id')},
        ),
    ]
