# Generated by Django 3.2.13 on 2022-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0016_complete_rowdimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='strike',
            field=models.BooleanField(default=False, help_text='Зачеркнутый'),
        ),
    ]
