# Generated by Django 3.2.13 on 2022-05-23 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0017_strike_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='columndimension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата обновления'),
        ),
    ]
