# Generated by Django 3.2.13 on 2022-06-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0018_add_columndimension_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodgroup',
            options={'ordering': ('-created_at',)},
        ),
    ]
