# Generated by Django 3.2.13 on 2022-06-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0019_alter_periodgroup_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('period', 'object_id')},
        ),
    ]
