# Generated by Django 3.2.14 on 2022-08-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0020_alter_division_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='error',
            field=models.CharField(choices=[('CYCLE_REF', 'cycle_ref')], default=None, help_text='Тип ошибки', max_length=20, null=True),
        ),
    ]
