# Generated by Django 3.2.15 on 2022-09-14 19:53

from django.db import migrations, models


def set_objects_name(apps, schema_editor):
    """Выносим имена дивизионов в документы.

    1. У нас тип дивизиона находиться в проекте и чтобы добраться до дивизиона необходимо получить
        document.period.project.division.objects.get(pk=document.object_id) - если выгружаем 100 документов то долго
    2. Может произойти смена названия дивизиона, что будет означать, что в документах резко поменяется название.

    Поле вычисляемое, обратной миграции нет.
    """
    from apps.dcis.models import Project
    Document = apps.get_model('dcis', 'Document')
    for document in Document.objects.all():
        project: Project = Project.objects.get(pk=document.period.project_id)
        names = project.division.objects.filter(pk=document.object_id).values_list('name', flat=True)
        if names:
            document.object_name = names[0]
            document.save(update_fields=('object_name',))


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0022_protected_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='object_name',
            field=models.CharField(help_text='Название дивизиона', max_length=512, null=True),
        ),
        migrations.RunPython(set_objects_name)
    ]
