# Generated by Django 3.2.15 on 2022-09-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0023_document_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='show_child',
            field=models.BooleanField(default=True, help_text='Показывать ли подведомственным'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='show_head',
            field=models.BooleanField(default=True, help_text='Показывать ли головам'),
        ),
    ]
