# Generated by Django 3.2.15 on 2022-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0023_document_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='number_format',
            field=models.TextField(help_text='Форматирование чисел', null=True),
        ),
    ]
