# Generated by Django 3.2.15 on 2022-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0023_document_object_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='versioning',
            field=models.BooleanField(default=False, help_text='Множество версий'),
        ),
    ]
