# Generated by Django 3.2.15 on 2022-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0024_auto_20220927_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='versioning',
            field=models.BooleanField(default=False, help_text='Множество версий'),
        ),
    ]
