# Generated by Django 3.2.15 on 2022-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0025_alter_attribute_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='attribute',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Позиция в выводе'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='default',
            field=models.TextField(help_text='Значение по умолчанию', null=True),
        ),
    ]
