# Generated by Django 3.2.15 on 2022-10-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0026_auto_20221001_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('key', 'period')},
        ),
    ]
