# Generated by Django 3.2.16 on 2022-10-10 13:15

from django.db import migrations, models


def set_number_format(apps, schema_editor):
    """Добавление форматирования чисел к ячейке."""
    from apps.dcis.models.sheet import KindCell
    Cell = apps.get_model('dcis', 'Cell')
    for cell in Cell.objects.all():
        if cell.kind == KindCell.NUMERIC:
            cell.number_format = '0.00'
            cell.save(update_fields=('number_format',))
        if cell.kind == KindCell.DATE:
            cell.number_format = 'dd.mm.yyyy'
            cell.save(update_fields=('number_format',))


def empty_reverse(apps, schema_editor):
    """Пустая функция для отката миграции, т.к. поле `number_format` является вычисляемым."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0027_alter_attribute_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='number_format',
            field=models.TextField(help_text='Форматирование чисел', null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='kind',
            field=models.CharField(choices=[('n', 'n'), ('s', 's'), ('f', 'f'), ('b', 'b'), ('inlineStr', 'inlineStr'), ('e', 'e'), ('str', 'str'), ('d', 'd'), ('time', 'time'), ('text', 'text'), ('money', 'money'), ('bigMoney', 'bigMoney'), ('fl', 'fl'), ('user', 'user'), ('department', 'department'), ('organization', 'organization'), ('classification', 'classification')], default='s', help_text='Тип значения', max_length=30),
        ),
        migrations.AlterField(
            model_name='columndimension',
            name='kind',
            field=models.CharField(choices=[('n', 'n'), ('s', 's'), ('f', 'f'), ('b', 'b'), ('inlineStr', 'inlineStr'), ('e', 'e'), ('str', 'str'), ('d', 'd'), ('time', 'time'), ('text', 'text'), ('money', 'money'), ('bigMoney', 'bigMoney'), ('fl', 'fl'), ('user', 'user'), ('department', 'department'), ('organization', 'organization'), ('classification', 'classification')], default='s', help_text='Тип значения', max_length=30),
        ),
        migrations.RunPython(set_number_format, empty_reverse)
    ]
