# Generated by Django 3.2.16 on 2022-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0028_number_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Является ли поле шаблоном'),
        ),
    ]
