# Generated by Django 3.2.16 on 2022-10-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0029_cell_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='extra_value',
            field=models.TextField(help_text='Дополнительное значение', null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='kind',
            field=models.CharField(choices=[('n', 'n'), ('s', 's'), ('f', 'f'), ('b', 'b'), ('inlineStr', 'inlineStr'), ('e', 'e'), ('str', 'str'), ('d', 'd'), ('time', 'time'), ('text', 'text'), ('money', 'money'), ('bigMoney', 'bigMoney'), ('fl', 'fl'), ('user', 'user'), ('department', 'department'), ('organization', 'organization'), ('classification', 'classification'), ('aggregation', 'aggregation')], default='s', help_text='Тип значения', max_length=30),
        ),
        migrations.AlterField(
            model_name='columndimension',
            name='kind',
            field=models.CharField(choices=[('n', 'n'), ('s', 's'), ('f', 'f'), ('b', 'b'), ('inlineStr', 'inlineStr'), ('e', 'e'), ('str', 'str'), ('d', 'd'), ('time', 'time'), ('text', 'text'), ('money', 'money'), ('bigMoney', 'bigMoney'), ('fl', 'fl'), ('user', 'user'), ('department', 'department'), ('organization', 'organization'), ('classification', 'classification'), ('aggregation', 'aggregation')], default='s', help_text='Тип значения', max_length=30),
        ),
        migrations.CreateModel(
            name='RelationshipCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_cells', to='dcis.cell')),
                ('to_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cells', to='dcis.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='cells',
            field=models.ManyToManyField(related_name='related_cells', through='dcis.RelationshipCells', to='dcis.Cell'),
        ),
    ]
