# Generated by Django 3.2.16 on 2022-10-31 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0030_add_curator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'sum'), ('avg', 'avg'), ('min', 'min'), ('max', 'max')], default=None, help_text='Механизм агрегации', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='value',
            name='extra_value',
            field=models.TextField(help_text='Дополнительное значение', null=True),
        ),
        migrations.CreateModel(
            name='RelationshipCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_cells', to='dcis.cell')),
                ('to_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_cells', to='dcis.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='cells',
            field=models.ManyToManyField(related_name='related_cells', through='dcis.RelationshipCells', to='dcis.Cell'),
        ),
    ]
