# Generated by Django 3.2.16 on 2022-11-09 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcis', '0033_add_add_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Комментарий', max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('document', models.ForeignKey(help_text='Документ', on_delete=django.db.models.deletion.CASCADE, to='dcis.document')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший комментарий', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
