# Generated by Django 3.2.16 on 2022-11-14 09:40

from django.db import migrations, models

from apps.dcis.helpers.cell import EXCEL_ERRORS_MAP


def set_default_error(apps, schema_editor):
    """Добавление значения ошибки по умолчанию."""
    Cell = apps.get_model('dcis', 'Cell')
    error_values_map = {et.value: e for et, e in EXCEL_ERRORS_MAP.items()}
    for cell in Cell.objects.all():
        if cell.default in error_values_map:
            cell.default_error = error_values_map[cell.default]
            cell.default = None
            cell.save(update_fields=('default', 'default_error',))
        elif cell.default in EXCEL_ERRORS_MAP.values():
            cell.default_error = cell.default
            cell.default = None
            cell.save(update_fields=('default', 'default_error',))


def reverse_default_error(apps, schema_editor):
    """Удаление значения ошибки по умолчанию."""
    Cell = apps.get_model('dcis', 'Cell')
    for cell in Cell.objects.all():
        if cell.default_error is not None:
            cell.default = cell.default_error
            cell.save(update_fields=('default',))


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0034_limitation_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='default_error',
            field=models.TextField(help_text='Значение ошибки по умолчанию', null=True),
        ),
        migrations.RunPython(set_default_error, reverse_default_error),
    ]
