# Generated by Django 3.2.16 on 2022-11-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0035_default_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='verified',
        ),
    ]
