# Generated by Django 3.2.16 on 2022-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0036_delete_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='attribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-12 19:01:17.679463', help_text='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Дата обновления'),
        ),
    ]
