# Generated by Django 3.2.16 on 2022-12-26 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_updated_by(apps, schema_editor):
    """Установка пользователя создавшего документ в качестве пользователя, обновившего документ."""
    Document = apps.get_model('dcis', 'Document')
    for document in Document.objects.all():
        document.updated_by = document.user
        document.save(update_fields=('updated_by',))


def empty_reverse(apps, schema_editor):
    """Пустая функция для отката миграции, т.к. поле `updated_by` является вычисляемым."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcis', '0038_add_document_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(help_text='Пользователь, обновивший документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_document_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, добавивший документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_updated_by, empty_reverse),
    ]
