# Generated by Django 3.2.16 on 2023-01-25 10:57

from django.db import migrations


def move_document_comments(apps, schema_editor):
    """Перемещение комментариев документов в блок комментариев."""
    Document = apps.get_model('dcis', 'Document')
    DocumentMessage = apps.get_model('dcis', 'DocumentMessage')
    User = apps.get_model('core', 'User')
    for document in Document.objects.all():
        user = document.user or document.period.user or User.objects.get(username='support@cbias.ru')
        DocumentMessage.objects.create(comment=document.comment, user=user, document=document)


def empty_reverse(apps, schema_editor):
    """Пустая функция для отката миграции."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0040_denormalize_document_last_status'),
    ]

    operations = [
        migrations.RunPython(move_document_comments, empty_reverse),
        migrations.RemoveField(
            model_name='document',
            name='comment',
        )
    ]
