# Generated by Django 3.2.16 on 2023-02-02 15:28

from django.db import migrations, models
import django.utils.timezone


def move_document_comments(apps, schema_editor):
    """Перемещение комментариев документов в блок комментариев."""
    Document = apps.get_model('dcis', 'Document')
    DocumentMessage = apps.get_model('dcis', 'DocumentMessage')
    User = apps.get_model('core', 'User')
    for document in Document.objects.all():
        user = document.user or document.period.user or User.objects.get(username='support@cbias.ru')
        DocumentMessage.objects.create(
            comment=document.comment,
            created_at=document.created_at,
            user=user,
            document=document)


def empty_reverse(apps, schema_editor):
    """Пустая функция для отката миграции."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0040_denormalize_document_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания'),
        ),
        migrations.RunPython(move_document_comments, empty_reverse),
        migrations.RemoveField(
            model_name='document',
            name='comment',
        ),
    ]
