# Generated by Django 3.2.16 on 2023-02-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0042_move_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstatus',
            name='check',
            field=models.CharField(default='', help_text='Действие при добавлении статуса в документ', max_length=250),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='addstatus',
            old_name='check',
            new_name='action',
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='archive_period',
            field=models.ForeignKey(help_text='Архивированный период', null=True, on_delete=django.db.models.deletion.CASCADE, to='dcis.period'),
        ),
    ]
