# Generated by Django 3.2.16 on 2023-04-06 14:13

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.dcis.models.methodical_support


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0043_delete_extra_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='methodical_support',
        ),
        migrations.CreateModel(
            name='PeriodMethodicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Название файла', max_length=255)),
                ('src', models.FileField(
                    upload_to=apps.dcis.models.methodical_support.file_directory_path,
                    help_text='Путь к файлу'
                )),
                ('deleted', models.BooleanField(default=False, help_text='Помечаем удаленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления файла')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления файла')),
                ('period', models.ForeignKey(
                    help_text='Период',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='dcis.period'
                )),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
