# Generated by Django 3.2.18 on 2023-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0043_add_achive_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='archive',
            field=models.BooleanField(default=False, help_text='Архивный период'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='color',
            field=models.CharField(default='#000000', help_text='Цвет текста', max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='sheets',
            field=models.ManyToManyField(help_text='Листы документа', to='dcis.Sheet'),
        ),
    ]
