# Generated by Django 3.2.18 on 2023-04-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0044_add_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='vertical_align',
            field=models.CharField(choices=[('top', 'top'), ('middle', 'middle'), ('bottom', 'bottom')], default=None, help_text='Вертикальное выравнивание', max_length=10, null=True),
        ),
    ]
