# Generated by Django 3.2.18 on 2023-04-17 13:58

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.dcis.models.methodical_support


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0045_alter_cell_vertical_align'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='methodical_support',
        ),
        migrations.CreateModel(
            name='PeriodMethodicalSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Название файла', max_length=255)),
                ('src', models.FileField(help_text='Путь к файлу', upload_to=apps.dcis.models.methodical_support.file_directory_path)),
                ('deleted', models.BooleanField(default=False, help_text='Помечаем удаленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления файла')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления файла')),
                ('period', models.ForeignKey(help_text='Период', null=True, on_delete=django.db.models.deletion.CASCADE, to='dcis.period')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
