# Generated by Django 3.2.18 on 2023-05-02 08:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.dcis.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('dcis', '0046_add_period_methodical_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Название файла', max_length=255)),
                ('src',
                 models.FileField(help_text='Путь к файлу', upload_to=apps.dcis.models.document.file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления файла')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления файла')),
                ('document', models.OneToOneField(
                    help_text='Скан документа',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='scan',
                    to='dcis.document'
                )),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='upload_scan',
            field=models.BooleanField(default=False, help_text='Можно ли загружать скан документа'),
        ),
    ]
